In [1]:
# Importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline

In [2]:
# Importing train dataset as df

df = pd.read_csv("Train.csv")
df.shape

(8523, 12)

In [3]:
df_test = pd.read_csv("Test.csv")

In [4]:
df.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            8523 non-null   object 
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object 
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object 
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object 
 7   Outlet_Establishment_Year  8523 non-null   int64  
 8   Outlet_Size                6113 non-null   object 
 9   Outlet_Location_Type       8523 non-null   object 
 10  Outlet_Type                8523 non-null   object 
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB


In [6]:
df.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
df[df['Item_Visibility'] == 0]

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
3              FDX07       19.200          Regular              0.0   
4              NCD19        8.930          Low Fat              0.0   
5              FDP36       10.395          Regular              0.0   
10             FDY07       11.800          Low Fat              0.0   
32             FDP33       18.700          Low Fat              0.0   
...              ...          ...              ...              ...   
8480           FDQ58          NaN          Low Fat              0.0   
8484           DRJ49        6.865          Low Fat              0.0   
8486           FDR20       20.000          Regular              0.0   
8494           NCI54       15.200          Low Fat              0.0   
8500           NCQ42       20.350          Low Fat              0.0   

                  Item_Type  Item_MRP Outlet_Identifier  \
3     Fruits and Vegetables  182.0950            OUT010   
4                 Household   53.8614            OUT013   
5              Baking Goods   51.4008            OUT018   
10    Fruits and Vegetables   45.5402            OUT049   
32              Snack Foods  256.6672            OUT018   
...                     ...       ...               ...   
8480            Snack Foods  154.5340            OUT019   
8484            Soft Drinks  129.9652            OUT013   
8486  Fruits and Vegetables   46.4744            OUT010   
8494              Household  110.4912            OUT017   
8500              Household  125.1678            OUT017   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
3                          1998         NaN               Tier 3   
4                          1987        High               Tier 3   
5                          2009      Medium               Tier 3   
10                         1999      Medium               Tier 1   
32                         2009      Medium               Tier 3   
...                         ...         ...                  ...   
8480                       1985       Small               Tier 1   
8484                       1987        High               Tier 3   
8486                       1998         NaN               Tier 3   
8494                       2007         NaN               Tier 2   
8500                       2007         NaN               Tier 2   

            Outlet_Type  Item_Outlet_Sales  
3         Grocery Store           732.3800  
4     Supermarket Type1           994.7052  
5     Supermarket Type2           556.6088  
10    Supermarket Type1          1516.0266  
32    Supermarket Type2          3068.0064  
...                 ...                ...  
8480      Grocery Store           459.4020  
8484  Supermarket Type1          2324.9736  
8486      Grocery Store            45.2744  
8494  Supermarket Type1          1637.8680  
8500  Supermarket Type1          1907.5170  

[526 rows x 12 columns]

In [8]:
df.duplicated().sum()

0

In [9]:
# Converting columns to categorical

df[['Item_Fat_Content', 'Item_Type', 'Outlet_Size',
    'Outlet_Location_Type', 'Outlet_Identifier', 'Outlet_Type']] = df[['Item_Fat_Content', 'Item_Type', 'Outlet_Size',
                                                                        'Outlet_Location_Type', 'Outlet_Identifier', 'Outlet_Type']].astype('category')

In [10]:
df['Item_Outlet_Sales'].describe()

count     8523.000000
mean      2181.288914
std       1706.499616
min         33.290000
25%        834.247400
50%       1794.331000
75%       3101.296400
max      13086.964800
Name: Item_Outlet_Sales, dtype: float64

In [11]:
(df == 0).sum(axis=0)

Item_Identifier                0
Item_Weight                    0
Item_Fat_Content               0
Item_Visibility              526
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Size                    0
Outlet_Location_Type           0
Outlet_Type                    0
Item_Outlet_Sales              0
dtype: int64

In [12]:
df['Item_Visibility'].replace(0, df['Item_Visibility'].mean(), inplace=True)

## NA value treatment

In [13]:
id_weight = df.pivot_table(values= 'Item_Weight', index= 'Item_Identifier')
id_weight

Item_Weight
Item_Identifier             
DRA12                 11.600
DRA24                 19.350
DRA59                  8.270
DRB01                  7.390
DRB13                  6.115
...                      ...
NCZ30                  6.590
NCZ41                 19.850
NCZ42                 10.500
NCZ53                  9.600
NCZ54                 14.650

[1555 rows x 1 columns]

In [14]:
# Replacing na values in 'Item_Weight' with mean

df['Item_Weight'] = df['Item_Weight'].fillna(df['Item_Weight'].mean())

In [15]:
# Replacing na values in 'Outlet_Size' with mode

df['Outlet_Size'] = df['Outlet_Size'].fillna(df['Outlet_Size'].mode()[0])

## Outlier treatment

In [16]:
# Returns Outliers

def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    # Calculate IQR
    IQR = Q3 - Q1

    # Define lower and upper bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[column][(df[column] < lower_bound) | (df[column] > upper_bound)]

    return outliers, lower_bound, upper_bound

In [17]:
# Print number of Outliers for each numeric columns

col_num = df.select_dtypes(include='float64')

for column in col_num :
    print(column, '\n', find_outliers(df, column)[0].count())

Item_Weight 
 0
Item_Visibility 
 173
Item_MRP 
 0
Item_Outlet_Sales 
 186


In [18]:
# Replacing outlier values with calculated upper and lower threshold values respectively

upper_thresh = find_outliers(df, 'Item_Outlet_Sales')[2]
lower_thresh = find_outliers(df, 'Item_Outlet_Sales')[1]

df['Item_Outlet_Sales'] = np.where(df['Item_Outlet_Sales'] > upper_thresh, upper_thresh, df['Item_Outlet_Sales'])
df['Item_Outlet_Sales'] = np.where(df['Item_Outlet_Sales'] < lower_thresh, lower_thresh, df['Item_Outlet_Sales'])

In [19]:
print(upper_thresh)
print(lower_thresh)

6501.8699
-2566.3261


## Splitting into train/test set

In [20]:
# Defining Independent and Dependent variables

X = df.drop(['Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Item_Outlet_Sales'], axis= 1)
y = df['Item_Outlet_Sales']

In [21]:
# Label Encoding categorical variables into integers

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

columns = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

for column in columns :
    X[column] = le.fit_transform(X[column])

In [22]:
X.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0         9.30                 1         0.016047          4  249.8092   
1         5.92                 2         0.019278         14   48.2692   
2        17.50                 1         0.016760         10  141.6180   
3        19.20                 2         0.066132          6  182.0950   
4         8.93                 1         0.066132          9   53.8614   

   Outlet_Size  Outlet_Location_Type  Outlet_Type  
0            1                     0            1  
1            1                     2            2  
2            1                     0            1  
3            1                     2            0  
4            0                     2            1

In [23]:
y.head()

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

In [24]:
# Splitting into Train and Test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [25]:
X_train = pd.get_dummies(X_train, drop_first=True, dtype='int8')
X_test = pd.get_dummies(X_test, drop_first=True, dtype='int8')

# Linear Regression

In [26]:
# Appying Linear Regression Model onto Train set

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [27]:
y_pred = lin_reg.predict(X_test)
y_pred

array([2001.29122459, 2132.14187195, 1235.20458641, ..., 1288.10013361,
       2203.58380066, 2335.86179266])

In [28]:
# Calculating R2 Score

from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.5071328005568867

# Polynomial Regression

In [29]:
# Calculating Polynomial Variables for train set

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X_train)

# Appying Polynomial Regression Model onto Train set

poly_reg = LinearRegression()
poly_reg.fit(X_poly, y_train)

LinearRegression()

In [30]:
y_pred = poly_reg.predict(poly.transform(X_test))
y_pred

array([1419.40223636, 2514.15238745, 1567.63449297, ...,  558.78317551,
       1796.23815016, 2396.5459349 ])

In [31]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.6018675675035512

# Support Vector Regression

In [32]:
# Applying scaling on Train sets

from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_y = StandardScaler()

X_svm = sc_x.fit_transform(X_train)
y_svm = sc_y.fit_transform(y_train.values.reshape(-1,1))

In [33]:
# Appying Support Vector Regression Model onto Train set

from sklearn.svm import SVR

svr_model = SVR(kernel = 'rbf')
svr_model.fit(X_svm, y_svm)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [34]:
y_pred = sc_y.inverse_transform(svr_model.predict(sc_x.transform(X_test)).reshape(-1,1))
y_pred

array([[1291.93360618],
       [2633.94179581],
       [1305.69271645],
       ...,
       [ 521.62571865],
       [1550.17215349],
       [2483.7612026 ]])

In [35]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.5977961541703498

# KNN Regressor

In [36]:
# Appying K-Nearest Neighbours Regression Model onto Train set

from sklearn.neighbors import KNeighborsRegressor

knn_reg = KNeighborsRegressor(n_neighbors= 5, metric= 'minkowski', p= 2)
knn_reg.fit(X_train, y_train)

KNeighborsRegressor()

In [37]:
y_pred = knn_reg.predict(X_test)

In [38]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.3321594026138368

# Decision Tree Regressor

In [39]:
# Appying Decision Tree Regression Model onto Train set

from sklearn.tree import DecisionTreeRegressor

dt_reg = DecisionTreeRegressor()
dt_reg.fit(X_train, y_train)

DecisionTreeRegressor()

In [40]:
y_pred = dt_reg.predict(X_test)
y_pred

array([2678.5134, 4119.9704, 1956.1204, ...,  184.4266, 2348.9424,
       2106.5912])

In [41]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.18780746623731848

# Random Forest Regressor

In [42]:
# Appying Random Forest Regression Model onto Train set

from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(n_estimators= 10)
rf_reg.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10)

In [43]:
y_pred = rf_reg.predict(X_test)
y_pred

array([1814.90422, 3567.82246, 1415.75712, ...,  309.46384, 1876.02466,
       2415.38924])

In [44]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.5193712745205388

# XGBoost Regressor

In [45]:
# Appying XGBoost Regression Model onto Train set

from xgboost import XGBRegressor

xgb_reg = XGBRegressor()
xgb_reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [46]:
y_pred = xgb_reg.predict(X_test)
y_pred

array([1270.8477 , 3622.9443 , 1580.2048 , ...,  164.28282, 1632.6517 ,
       3145.1028 ], dtype=float32)

In [47]:
# Calculating R2 Score

r2_score(y_test, y_pred)

0.5164179934718511

## By 0.6 r2 score, poly_reg (Polynomial Regression) is best fit for this dataset

In [48]:
# Performing Cross Validation on Train sets using Polynomial Regression model

from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator= poly_reg, X= X_train, y= y_train, cv= 10, scoring='r2')
print('Mean Accuracy : {:.2f} %'.format(accuracies.mean()*100))
print('Standard Deviation : {:.2f} %'.format(accuracies.std()*100))
print(accuracies)

Mean Accuracy : 51.69 %
Standard Deviation : 2.86 %
[0.54343235 0.53833124 0.51220653 0.50735039 0.48036389 0.51161865
 0.53888464 0.51938229 0.45926741 0.55840979]


## Predicting the test dataset

In [49]:
df_test.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility    Item_Type  \
0           FDW58       20.750          Low Fat         0.007565  Snack Foods   
1           FDW14        8.300              reg         0.038428        Dairy   
2           NCN55       14.600          Low Fat         0.099575       Others   
3           FDQ58        7.315          Low Fat         0.015388  Snack Foods   
4           FDY38          NaN          Regular         0.118599        Dairy   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year Outlet_Size  \
0  107.8622            OUT049                       1999      Medium   
1   87.3198            OUT017                       2007         NaN   
2  241.7538            OUT010                       1998         NaN   
3  155.0340            OUT017                       2007         NaN   
4  234.2300            OUT027                       1985      Medium   

  Outlet_Location_Type        Outlet_Type  
0               Tier 1  Supermarket Type1  
1               Tier 2  Supermarket Type1  
2               Tier 3      Grocery Store  
3               Tier 2  Supermarket Type1  
4               Tier 3  Supermarket Type3

In [50]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5681 entries, 0 to 5680
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            5681 non-null   object 
 1   Item_Weight                4705 non-null   float64
 2   Item_Fat_Content           5681 non-null   object 
 3   Item_Visibility            5681 non-null   float64
 4   Item_Type                  5681 non-null   object 
 5   Item_MRP                   5681 non-null   float64
 6   Outlet_Identifier          5681 non-null   object 
 7   Outlet_Establishment_Year  5681 non-null   int64  
 8   Outlet_Size                4075 non-null   object 
 9   Outlet_Location_Type       5681 non-null   object 
 10  Outlet_Type                5681 non-null   object 
dtypes: float64(3), int64(1), object(7)
memory usage: 488.3+ KB


In [51]:
df_test.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [52]:
df_test[['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Identifier', 'Outlet_Type']] = df_test[['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Identifier', 'Outlet_Type']].astype('category')

In [53]:
id_weight = df_test.pivot_table(values= 'Item_Weight', index= 'Item_Identifier')
id_weight

Item_Weight
Item_Identifier             
DRA12                 11.600
DRA24                 19.350
DRA59                  8.270
DRB01                  7.390
DRB13                  6.115
...                      ...
NCZ30                  6.590
NCZ41                 19.850
NCZ42                 10.500
NCZ53                  9.600
NCZ54                 14.650

[1527 rows x 1 columns]

In [54]:
df_test['Item_Weight'] = df_test['Item_Weight'].fillna(df['Item_Weight'].mean())

In [55]:
df_test['Outlet_Size'] = df_test['Outlet_Size'].fillna(df['Outlet_Size'].mode()[0])

In [56]:
# Returns Outliers
def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    # Calculate IQR
    IQR = Q3 - Q1

    # Define lower and upper bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[column][(df[column] < lower_bound) | (df[column] > upper_bound)]

    return outliers, lower_bound, upper_bound

In [57]:
col_num = df_test.select_dtypes(include='float64')

for column in col_num :
    print(column, '\n', find_outliers(df_test, column)[0].count())

Item_Weight 
 0
Item_Visibility 
 113
Item_MRP 
 0


In [58]:
df_test.drop(['Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year'], axis= 1, inplace= True)

In [59]:
# Label Encoding categorical variables into integers

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

columns = ['Item_Fat_Content', 'Item_Type', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

for column in columns :
    df_test[column] = le.fit_transform(df_test[column])

In [60]:
# Predicting test set

df_pred = poly_reg.predict(poly.transform(df_test))

df_test['Item_Outlet_Sales'] = pd.DataFrame(df_pred)

In [61]:
df_test.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0    20.750000                 1         0.007565         13  107.8622   
1     8.300000                 4         0.038428          4   87.3198   
2    14.600000                 1         0.099575         11  241.7538   
3     7.315000                 1         0.015388         13  155.0340   
4    12.857645                 2         0.118599          4  234.2300   

   Outlet_Size  Outlet_Location_Type  Outlet_Type  Item_Outlet_Sales  
0            1                     0            1        1616.694572  
1            1                     1            1        1280.713358  
2            1                     2            0         701.768632  
3            1                     1            1        2375.103286  
4            1                     2            3        5611.110581

In [62]:
df['Item_Outlet_Sales'].describe()

count    8523.000000
mean     2156.313016
std      1624.863069
min        33.290000
25%       834.247400
50%      1794.331000
75%      3101.296400
max      6501.869900
Name: Item_Outlet_Sales, dtype: float64

In [63]:
df_test['Item_Outlet_Sales'].describe()

count    5681.000000
mean     2160.647291
std      1285.569403
min      -635.903014
25%      1093.264899
50%      2103.337880
75%      3084.251578
max      5871.487042
Name: Item_Outlet_Sales, dtype: float64